### ISSUE TITLE
included post nesting is still borked

### ISSUE THREAD

**Issue by papertek** [CamelliaCommunity/Wiki#133]
![image](https://github.com/CamelliaCommunity/Wiki/assets/72106503/c555847f-daf2-4c97-b94e-0c312ee43e2b)

included post nesting is supposed to function as folders in the file structure. the screenshot above shows how broken it is at the moment

**Comment by Aisuruneko** [comment]
![image](https://github.com/CamelliaCommunity/Wiki/assets/30270106/bc799af0-ad09-43e4-a3f3-f3fdfac25881)

What we expect to at least have, hopefully soon. Nesting is a bit weird (and still in beta) for this CMS. May not be able to do with current state. We'll see.
