### ISSUE TITLE
incomplete articles need to be hidden

### ISSUE THREAD

**Issue by papertek** [CamelliaCommunity/Wiki#136]
per camellia's request, we need to hide them

I'm thinking of hiding them from the homepage and displaying them in a special page, because camellia also mentioned we need to keep things "attractive" with editing incomplete articles

big fricking "edit this page!" button in the list of incomplete articles

**Comment by Aisuruneko** [comment]
We are able to move things to the Workflow ,and since the CMS uses Beta, we can merge changes to Beta and allow users to see what it looks like. This should allow us to unpublish them in production.

**Comment by papertek** [comment]
"I THINK THIS IS GOOD TO CLOSE" - MATT FISHBACH EDWARDS
